version = 0.1
[default.deploy.parameters]
stack_name = "healthy-basket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "healthy-basket"
disable_rollback = true
image_repositories = [""]
